### ISSUE TITLE
What are the events supposed to be

### ISSUE THREAD

**Issue by unseeyou** [AndrewPerson/SBHS-Random-Data#1]
Right now it's just an empty list

**Comment by AndrewPerson** [comment]
I think the comment says it all:
`//No idea what events are`

**Comment by AndrewPerson** [comment]
But in all honesty, I just made them empty because that's all the api ever seems to return. Also, this mimics the older version of the school api, so it may no longer even include events.

**Comment by unseeyou** [comment]
> But in all honesty, I just made them empty because that's all the api ever seems to return. Also, this mimics the older version of the school api, so it may no longer even include events.

ok then
